'use client';

import { useState } from 'react';
import { Clapperboard, File, Folder, FolderOpen, Pencil, Plus, Trash2 } from 'lucide-react';

export type ProjectTreeShot = { id: string; title: string; detail: string; meta?: string; state: string };
export type ProjectTreeAsset = { name: string; type: 'character' | 'scene' | 'clothing' | 'prop' | 'video' | 'audio' | 'custom'; thumbnail?: string };
type Props = { projectName: string; assets?: ProjectTreeAsset[]; outputFiles?: string[] | null; shots: ProjectTreeShot[]; activeShot: number; onSelectShot: (i: number) => void; onAddShot?: () => void; onAddAsset?: () => void; onDeleteAsset?: (asset: ProjectTreeAsset) => void; onRenameShot?: (i: number) => void; onDeleteShot?: (i: number) => void; projects?: { name: string }[]; activeProjectName?: string; onSelectProject?: (n: string) => void; onRemoveProject?: (n: string) => void };

const assetTypes = [['character', '角色'], ['scene', '场景'], ['clothing', '服装'], ['prop', '道具'], ['video', '视频'], ['audio', '音频'], ['custom', '自定义']] as const;

export function ProjectTree(p: Props) {
  const [openProjects, setOpenProjects] = useState<Record<string, boolean>>({});
  const [openAssets, setOpenAssets] = useState(true);
  const [openShots, setOpenShots] = useState(true);
  const [openOutput, setOpenOutput] = useState(true);
  const visibleAssetTypes = assetTypes
    .map(([type, label]) => ({
      type,
      label,
      items: (p.assets ?? []).filter((asset) => asset.type === type),
    }))
    .filter(({ items }) => items.length > 0);
  const content = <div className="ml-3">
    <div className="flex items-center gap-1"><button type="button" onClick={() => setOpenAssets(!openAssets)} className="flex min-w-0 flex-1 gap-1.5 py-1 text-left text-zinc-300"><FolderOpen className="size-3.5" />资产</button><button type="button" onClick={p.onAddAsset} className="grid size-6 place-items-center rounded text-zinc-400 hover:bg-muted hover:text-foreground" aria-label="添加资产" title="添加资产"><Plus className="size-3.5" /></button></div>
    {openAssets && <>{visibleAssetTypes.map(({ type, label, items }) => <div key={type} className="ml-3 mt-2"><div className="flex items-center gap-1.5 py-1 text-zinc-400"><Folder className="size-3" />{label}</div><div className="ml-5 space-y-1">{items.map((asset) => <div key={asset.name} className="group flex items-center gap-1"><span className="grid size-7 shrink-0 place-items-center overflow-hidden rounded bg-muted">{asset.thumbnail ? <img src={asset.thumbnail} alt="" className="size-full object-cover" /> : <File className="size-3" />}</span><span className="min-w-0 flex-1 truncate rounded px-1 py-1 text-zinc-500">{asset.name}</span><button type="button" onClick={(event) => { event.preventDefault(); event.stopPropagation(); p.onDeleteAsset?.(asset); }} className="grid size-6 shrink-0 place-items-center rounded text-zinc-500 transition hover:bg-red-500/15 hover:text-red-300" aria-label={`删除${label} ${asset.name}`} title={`删除${label}`}><Trash2 className="size-3" /></button></div>)}</div></div>)}</>}
    <div className="mt-2 flex items-center gap-1"><button type="button" onClick={() => setOpenShots(!openShots)} className="flex flex-1 gap-1.5 py-1 text-left text-zinc-300"><FolderOpen className="size-3.5" />片段</button><button type="button" onClick={p.onAddShot} className="grid size-6 place-items-center"><Plus className="size-3" /></button></div>
    {openShots && <div className="space-y-1.5">{p.shots.map((s, i) => { const dot = s.state === '已完成' ? 'bg-emerald-400' : s.state === '生成中' ? 'bg-amber-400 animate-pulse' : s.state === '失败' ? 'bg-red-400' : 'bg-zinc-500'; return <div key={s.id} className={`group relative rounded-xl border ${p.activeShot === i ? 'border-primary/35 bg-primary/10' : 'border-transparent hover:bg-muted/50'}`}><button type="button" onClick={() => p.onSelectShot(i)} className="flex w-full items-center gap-2.5 p-2.5 text-left"><span className={`grid size-9 shrink-0 place-items-center rounded-lg ring-1 ${p.activeShot === i ? 'bg-primary/15 text-primary ring-primary/20' : 'bg-[#181a1f] text-zinc-500 ring-white/6'}`}><Clapperboard className="size-4" /></span><span className="min-w-0 flex-1"><span className="block truncate text-[10px] text-zinc-200">{s.id} · {s.title}</span><span className="mt-1 block truncate text-[9px] text-zinc-500">{s.detail}</span><span className="mt-1 flex items-center gap-1.5 text-[9px] text-zinc-500"><span className={`size-1.5 rounded-full ${dot}`} />{s.state}</span></span></button><button type="button" onClick={() => p.onRenameShot?.(i)} className="absolute right-2 top-2 hidden rounded p-1 text-zinc-500 transition-colors hover:bg-primary/15 hover:text-primary group-hover:block" aria-label="编辑片段名称"><Pencil className="size-3" /></button><button type="button" onClick={() => p.onDeleteShot?.(i)} className="absolute bottom-2 right-2 hidden rounded p-1 text-zinc-500 transition-colors hover:bg-red-500/15 hover:text-red-300 group-hover:block" aria-label="删除片段"><Trash2 className="size-3" /></button></div>; })}</div>}
    {p.outputFiles !== undefined && p.outputFiles !== null && <><div className="mt-2 flex items-center gap-1"><button type="button" onClick={() => setOpenOutput(!openOutput)} className="flex flex-1 gap-1.5 py-1 text-left text-zinc-300"><FolderOpen className="size-3.5" />输出</button></div>{openOutput && <div className="ml-5 space-y-1">{p.outputFiles.length ? p.outputFiles.map((name) => <div key={name} className="flex min-w-0 items-center gap-1.5 py-1 text-zinc-500"><File className="size-3 shrink-0" /><span className="truncate">{name}</span></div>) : <span className="block py-1 text-[9px] text-zinc-600">暂无输出文件</span>}</div>}</>}
  </div>;
  if (!p.projects?.length) return <p className="px-1 py-2 text-[10px] text-zinc-500">暂无项目，请先新建或导入项目</p>;
  return <div className="space-y-1 text-[10px]">{p.projects.map((project) => { const open = p.activeProjectName === project.name && openProjects[project.name] !== false; return <div key={project.name}><div className="flex items-center gap-1"><button type="button" onClick={() => { p.onSelectProject?.(project.name); setOpenProjects((v) => ({ ...v, [project.name]: p.activeProjectName === project.name ? !open : true })); }} className={`flex min-w-0 flex-1 items-center gap-1.5 rounded px-1.5 py-1.5 text-left ${p.activeProjectName === project.name ? 'bg-primary/10 text-primary' : 'text-zinc-400 hover:bg-muted'}`}><FolderOpen className="size-3.5 shrink-0" /><span className="truncate">{project.name}</span></button><button type="button" onClick={(event) => { event.stopPropagation(); p.onRemoveProject?.(project.name); }} className="grid size-7 shrink-0 items-center place-items-center rounded text-zinc-500 transition-colors hover:bg-red-500/15 hover:text-red-300" aria-label={`删除项目 ${project.name}`} title="删除项目"><Trash2 className="size-3.5" /></button></div>{open && content}</div>; })}</div>;
}
